name: string_helper
description: String helpers
version: 0.0.1
author: ntaoo <ntaoo.g@gmail.com>
homepage: https://github.com/ntaoo/string_helper

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  quiver: ^0.25.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
